### ISSUE TITLE
Annotation missing for an image?

### ISSUE THREAD

**Issue by sigmoidfroid** [sartorius-research/LIVECell#1]
Hi, 

First, thanks a lot for releasing this amazing resource of cell annotations! 

After downloading the data via `aws s3 sync s3://livecell-dataset .` I noticed that the training image `MCF7_Phase_E4_1_00d00h00m_1.tif` seems to have no corresponding annotation mask:

```
cd LIVECell_dataset_2021/

fname=MCF7_Phase_E4_1_00d00h00m_1.tif

find images/ -name $fname
# images/livecell_train_val_images/MCF7/MCF7_Phase_E4_1_00d00h00m_1.tif

grep -o $fname annotations/LIVECell/*json
# <no output>
``` 

compared to e.g. `MCF7_Phase_F4_1_00d00h00m_1.tif`

```
fname=MCF7_Phase_F4_1_00d00h00m_1.tif

find images/ -name $fname
# images/livecell_train_val_images/MCF7/MCF7_Phase_F4_1_00d00h00m_1.tif

grep -o $fname annotations/LIVECell/*json
# annotations/LIVECell/livecell_coco_train.json:MCF7_Phase_F4_1_00d00h00m_1.tif

```

**Comment by ChristofferEdlund** [comment]
Hey @sigmoidfroid. This is a miss on our end and that image has now been removed. Since it was not part of any model training 
(due to lack of annotation) it should not have any effect on reproducing our results.

Thank you for taking the time to point this out, we appreciate it!
