### ISSUE TITLE
Single cell annotation for SK-OV-3 for test seems broken

### ISSUE THREAD

**Issue by naivete5656** [sartorius-research/LIVECell#12]
Hello!

Thank you to upload the great dataset.

I try to perform on a single SK-OV-3 cell condition by using skov3/test.json.
However, the test.json of a single SK-OV-3 seems broken.
(https://livecell-dataset.s3.eu-central-1.amazonaws.com/LIVECell_dataset_2021/annotations/LIVECell_single_cells/skov3/test.json)
I try to open this JSON file by using pycocotools.
But, JSON decoder error occurs (following error).
![image](https://user-images.githubusercontent.com/30153024/151168288-e7e7ace6-aa2d-4c5f-94d6-81e1a2f2ca47.png)

By observing json file, this file seems to end in the middle of the description.
![image](https://user-images.githubusercontent.com/30153024/151169054-3598a75f-cd01-4886-b3bb-8e2cdbe0c58e.png)
Other files end with a license description.
Is this file correct?

Best regard

**Comment by ChristofferEdlund** [comment]
Hey @naivete5656, thank you for bringing this to our attention.

The test file for SK-OV-3 was indeed missing information and has been updated.

Kindly,
Christoffer
