### ISSUE TITLE
conver json to npy

### ISSUE THREAD

**Issue by EdwardZhao1991** [sartorius-research/LIVECell#13]
Hi,

Thanks for sharing the great work.

I'm not familiar with coco, could you please share some code about converting the `livecell_coco_train.json` annotation to npy?
The expected outputs are as follows
```python
A172_Phase_A7_1_00d00h00m_1.npy  # dtype=np.uint32
MCF7_Phase_E4_1_02d00h00m_2.npy
A172_Phase_A7_1_00d00h00m_2.npy
MCF7_Phase_E4_1_02d00h00m_3.npy
```

**Comment by EdwardZhao1991** [comment]
Hi @RickardSjogren @ChristofferEdlund,

I'm sorry to bother you. Any comments would be highly appreciated.

**Comment by ChristofferEdlund** [comment]
Hey there @EdwardZhao1991!

Could you elaborate a bit on the numpy format you wish to convert the json annotations to?

**Comment by EdwardZhao1991** [comment]
Hi @ChristofferEdlund ,

I hope the numpy format is a 2D matrix that has the same size as the original image. The values are the instance cell labels where the label value ranges from 0 to the number of cells. 
Just like the format in deepcell https://datasets.deepcell.org/.

For example
```python
import cv2

img = cv2.imread('./images/livecell_train_val_images/A172_Phase_A7_1_00d00h00m_1.tif') # shape (520,704,3)
gt = np.load('./masks/A172_Phase_A7_1_00d00h00m_1.npy') # shape (520,704), dtype=np.int32, each cell is labelled with a unique value (e.g., 1,2,3,...)

```

**Comment by ChristofferEdlund** [comment]
Thank you for the clarification of what type of conversion you are looking for @EdwardZhao1991.

Have you checked if deepcell provide any transformation from COCO to their format?

If you want to do it manually i suggest using the [pycocotools library](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py), here is an example that I have not verified will work but should point you in the right direction:


```
from pycocotools.coco import COCO
import numpy as np
coco_anno = COCO("LIVECELL_val_coco.json")

img_ids = coco_anno.getImgIds()
ann_ids = coco_anno.getAnnIds()

# Generate mask
mask = None

# Iterate over each image
for img_id in img_ids:
    ann_ids = coco_anno.getAnnIds(imgIds=img_id)
    #Generate an empty mask
    mask = np.zeros_like(coco_anno.annToMask(coco_anno.anns[anns_ids[0]]))
    
    #Iterate over all annotations in one image
    for i, ann in enumerate(ann_ids):

       # Generate a mask from the annotation
        instance_mask = coco_anno.annToMask(coco_ann.anns[ann])
        
        # Add this mask instance to the mask containing all instances
        mask = mask + (instance_mask *i+1)
    
    # Take name from the image we generated a mask from and save the mask in numpy format
    img_info = coco_anno.imgs[img_id]
    name = img_info['file_name'].replace[".tif", ".npy"]
    np.save(directory_name + "/" + name, mask)

```


Please note that this solution does not support overlapping instances and just adding them together as above will mess things up (since we naively add the values). 

I hope this will help you out! =)

**Comment by EdwardZhao1991** [comment]
Hi @ChristofferEdlund ,

Thank for your code very much. It's very useful for me since I have no idea about coco json format.

I visualize some annotations. 
> Ignoring the overlapping issue as you mentioned:)

![image](https://user-images.githubusercontent.com/96451740/153728729-21d1b930-7f54-4fd1-a8f8-4f9114c3f996.png)

![image](https://user-images.githubusercontent.com/96451740/153728817-9fdc9dc1-6d59-469f-b66b-5c053fe5dd90.png)



I'm not an expert on the label-free images. **The objects in the yellow circle are not cells, right?**

**Comment by EdwardZhao1991** [comment]
Hi @ChristofferEdlund ,

Would it be possible for you to share the code to draw the following pictures?

![image](https://user-images.githubusercontent.com/96451740/154867657-64fd6ff7-fe74-497e-b86d-19e81ceae2ec.png)
