### ISSUE TITLE
Detectron2-ResNeSt does not support the fast_eval_api operation

### ISSUE THREAD

**Issue by zhouzhouhhh** [sartorius-research/LIVECell#16]
Hello, I am using your code to build anchor based model, 
I executed 

```
git clone https://github.com/chongruo/detectron2-ResNeSt
python -m pip install -e detectron2-ResNeSt
replaced detectron2-ResNeSt/detectron2/evaluation/coco_evaluation.py with code/coco_evaluation.py from livecell codebase
```
but after running It will prompt that there is no fast_eval_api in detectron2.evaluation,It seems to be because detectron2-ResNeSt does not currently support the fast_eval_api operation in detectron2?

**Comment by ChristofferEdlund** [comment]
Hi there @zhouzhouhhh!

You are correct, the resNeSt implementation does not support the fast-coco-eval api, I have uploaded a pip package that you can use to install that API and run the evaluations using the faster C++ implementations called [fast-coco-eval](https://pypi.org/project/fast-coco-eval/)

You should be able to install it with:
`pip install fast-coco-eval`

Let me know if installing it with pip will solve your problem.

Kindly,
Christoffer
