### ISSUE TITLE
Could you please provide your package version for the anchor free model?

### ISSUE THREAD

**Issue by HXuSz11** [sartorius-research/LIVECell#18]
Now I am using python 3.6, pytorch 1.5.0 and detectron2 v0.2. The problem that I encounter is that the centermask2 model now import a file that the detectron2 v 0.2 does not have: 
centermask2/centermask/evaluation/coco_evaluation.py", line 27, in <module>
    from detectron2.utils.file_io import PathManager
ModuleNotFoundError: No module named 'detectron2.utils.file_io'

**Comment by RickardSjogren** [comment]
Hi @szxuhongye , as specified in the paper, the anchor-free model uses Detectron2 v0.3, Python  v.3.7.7 and PyTorch v.1.5.0
