### ISSUE TITLE
Conversion of model predictions to instance masks fails

### ISSUE THREAD

**Issue by constantinpape** [sartorius-research/LIVECell#19]
Hi @RickardSjogren,
I managed to set-up the environment for the anchor-free model now and also to run it (for the LiveCELL val data as well as for some test data from our Incucytes). However, I can't figure out how to extract the cell instance segmentation results from the output of the run:
The output directory has a subfolder `inference`, that contains the file `coco_instance_results.json`. However, this file is not in a valid coco format:
```python
from pycocotools.coco import COCO
COCO("inference/coco_instance_results.json")
```
fails with 
```
Traceback (most recent call last):
  File "/home/uni02/UMIN/pape41/Work/my_projects/incucyte_projects/livecell_models/to_imag$
s.py", line 36, in <module>
    annotations_to_masks("livecell-out/inference/coco_instances_results.json", "test-out/p$
edictions")
  File "/home/uni02/UMIN/pape41/Work/my_projects/incucyte_projects/livecell_models/to_image
s.py", line 10, in annotations_to_masks
    coco_anno = COCO(annotation_file)
  File "/home/uni02/UMIN/pape41/Work/software/conda/mambaforge/envs/main310/lib/python3.10/
site-packages/pycocotools/coco.py", line 83, in __init__
    assert type(dataset)==dict, 'annotation file format {} not supported'.format(type(datas
et))
AssertionError: annotation file format <class 'list'> not supported
```
and indeed the json contains a list that does not look like valid coco instance annotations:
```
[...
 {'image_id': 1,
  'category_id': 1,
  'bbox': [161.37379455566406,
   354.2332763671875,
   21.690078735351562,
   54.1363525390625],
  'score': 0.817893385887146,
  'segmentation': {'size': [848, 1280],
   'counts': '_aV47Uj05]Oc0M2N1O00O2M1010O101O10O2O1O1N2N2N3K9E]S\\l0'},
  'mask_score': 0.7007805705070496},
 ...]
```
Any idea on how to extract instance annotations from these results, or how to change the settings in order to obtain proper coco instance annotations?

For some more detail on how I ran this:
- I used the `Anchor free/Livecell` model (https://github.com/sartorius-research/LIVECell/blob/main/model/anchor_free/livecell_config.yaml)
- And then follow the steps as described here: https://github.com/sartorius-research/LIVECell/tree/main/model#evaluate to run evaluation.

**Comment by constantinpape** [comment]
I have also set up an environment for the anchorbased model now and could run inference with it, but I run into the same issues when trying to convert the prediction result to instance segmentations.

**Comment by RickardSjogren** [comment]
Hi @constantinpape , can you please share information on your environment? Which Python, Pytorch and package-versions are you using?

**Comment by constantinpape** [comment]
I made it work using the [detectron Prediction API](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5) now. This is more flexible for running prediction in general, because it removes the need to prepare coco annotation files for the input data.

It would still be nice to understand why the default method is not working though in order to validate my current solution (qualitatively it's working good).

Here's the environment details (for the anchor-free model):
- python: 3.10.6
- pytorch: 1.12.1
- detectron2: 0.6
- centermask2: current master

(I don't believe that the python or pytorch version should influence this though, since it's working in principle. My best guess would be some change in detectron)
