### ISSUE TITLE
What is mask_score?

### ISSUE THREAD

**Issue by XunDejin** [sartorius-research/LIVECell#2]
Hello, you have done a very great job on cell segmentation. I want to use the coco_evaluation.py you public to evaluate the performance of my model. I have read your code but have a question: 
          What does mask_score(here replace score) mean in the code ? Is it IoU of (pred instance ) and (gt instance) for each instance in a image?
Thank you for answering my question!

**Comment by ChristofferEdlund** [comment]
Hi there @XunDejin, we are delighted to hear that people such as you are using the LIVECell resources.

The evaluation script is based on work done by [youngwanLEE](https://github.com/youngwanLEE/centermask2/commits?author=youngwanLEE) in his [CenterMask2 repo](https://github.com/youngwanLEE/centermask2) but modified by us to evaluate many more instances per image.

The mask_score is a metric that i think is introduced in the CenterMask2 code and is defined as box scores * maskiou per instance. You can find the code that calculates and attaches the score to each instance [here](https://github.com/youngwanLEE/centermask2/blob/badd4878cb493d7432bbc370314d938ec99cca94/centermask/modeling/centermask/maskiou_head.py#L50).

I hope that gave you some clarity.

**Comment by XunDejin** [comment]
Thank you very much for answering my question! 
I will study and try it.
