### ISSUE TITLE
Unable to parse annotations using pycocotools package

### ISSUE THREAD

**Issue by calebhallinan** [sartorius-research/LIVECell#4]
Hello! 

I have downloaded the images and the corresponding .json files of the annotations for both the entire dataset and individual cell lines. However, when attempting to read the .json files for any of the annotations (ex. 'livecell_a172_val.json' or 'livecell_bv2_test.json') I get the error message shown below:

<img width="622" alt="Screen Shot 2021-10-13 at 11 37 58 AM" src="https://user-images.githubusercontent.com/66436845/137166677-9d219803-4ee7-4b0d-a581-026dee05a3d9.png">

I have researched the topic online and have tried a few "fixes", but am still having trouble with this issue. My hope is the extract the annotations as images to view them in order to later on evaluate the performance of a model.

Is there any chance you may know how to fix this issue?

**Comment by caleb-hallinan** [comment]
Hi Christoffer,

It seems the links I used originally to download the .json file for the datasets was bad. I'm unsure of how that happened, but upon trying the link you attached as well as redownloading them it seems to have been the trick!

Guess you should always start by redownloading things... sorry about that but thank you for your quick response!

Caleb

**Comment by joeleonard212** [comment]
Hi, since I'm experiencing the same problem with the train/test/val annotations and also with the single cell lines annotations, could you please re-post here all the correct links to the annotations ? Thanks

**Comment by ChristofferEdlund** [comment]
Hi @joeleonard212 

Could you please provide me the links since I am not able to reproduce the error when downloading annotations from:

https://sartorius-research.github.io/LIVECell/

**Comment by joeleonard212** [comment]
http://livecell-dataset.s3.eu-central-1.amazonaws.com/LIVECell_dataset_2021/annotations/LIVECell/livecell_coco_train.json
http://livecell-dataset.s3.eu-central-1.amazonaws.com/LIVECell_dataset_2021/annotations/LIVECell/livecell_coco_val.json
http://livecell-dataset.s3.eu-central-1.amazonaws.com/LIVECell_dataset_2021/annotations/LIVECell/livecell_coco_test.json

Using these from the github homepage I was facing the problem. Now I just downloaded everything with the AWS CLI and the annotations file are workiing fine, pycoco is creating the indexes and everything. I dunno but I solved. Thanks

**Comment by joeleonard212** [comment]
Using the CLI, I'm still facing problems while trying to download models for specific cell lines.

![Screenshot_20211206_173543](https://user-images.githubusercontent.com/35630044/144885245-e832c9f2-d9a3-4d82-9546-db6e47b8fe17.png)

I tried again indiicating the directory for the specific model I needed (for example: aws s3 sync s3://livecell-dataset/LIVECell_dataset_2021/models/Anchor_free/SHSY5Y/ . ) but the error is the same ever. Maybe something I should change in the aws confiigure for my IAM ?

**Comment by ChristofferEdlund** [comment]
@joeleonard212 

I am afraid that I am not able to reproduce your errors, using the links you provided I encounter no problems loading the annotations:

```
from pycocotools import coco
path = "livecell_coco_train.json"

anno = coco.COCO(path)
loading annotations into memory...
Done (t=23.37s)
creating index...
index created!
```

Got same result for train, val and test.

Regarding the CLI, perhaps @RickardSjogren might have some insight into what might be the problem?

**Comment by joeleonard212** [comment]
It's ok, the annotations are working now. About the models, as I said I was able to download everything except the folders in my previous screenshot. Thanks for the support

**Comment by ChristofferEdlund** [comment]
@joeleonard212 

Happy that the annotations are working, for the models you should be able to download them from the links [found here](https://github.com/sartorius-research/LIVECell/tree/main/model) if you have problems with the CLI.

**Comment by joeleonard212** [comment]
Same issue with the nucler_count_benchmark

Can you provide direct link for that ? The download with aws cli is avaible only for A172_counts.json and A549_counts.json.
4 files left are showing the same error as upon
