### ISSUE TITLE
Strange predictions on training images

### ISSUE THREAD

**Issue by csmolnar** [sartorius-research/LIVECell#6]
I am trying to use the trained LIVECell model.
To do so, first I have set up a google colab environment, and have tried to make predictions on some of the original training images.
I followed the installation steps for LIVECell, and I combined it with a general Detectron2 model visualization tutorial.

Here is the main code I use:

```
# Register training dataset
from detectron2.data.datasets import register_coco_instances
from detectron2.data import MetadataCatalog, DatasetCatalog

register_coco_instances("LIVECell", {}, data_path + "livecell_coco_train.json", data_path + "/images/livecell_train_val_images")
cells_metadata = MetadataCatalog.get("LIVECell")
dataset_dicts = DatasetCatalog.get("LIVECell")

# Load trained model
from detectron2.engine import DefaultTrainer
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg

cfg = get_cfg()
cfg.merge_from_list(['MODEL.WEIGHTS', os.path.join(models_path, "LIVECell_anchor_free_model.pth")])
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.25   # set the testing threshold for this model
predictor = DefaultPredictor(cfg)

# Predict on training images
from google.colab.patches import cv2_imshow
from detectron2.utils.visualizer import Visualizer
from detectron2.utils.visualizer import ColorMode

d = dataset_dicts[300] # choosing a random image
img = cv2.imread(d["file_name"])
outputs = predictor(img)
instances = outputs['instances']
v = Visualizer(img[:, :, ::-1],
                   scale=1, 
                   instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
    )
v = v.draw_instance_predictions(instances.to("cpu"))
cv2_imshow(v.get_image()[:, :, ::-1])
```

And this is what I get as the result

![pred_image300](https://user-images.githubusercontent.com/18211142/140103586-ec1b4c4a-4ea7-4f43-a0bf-7628af61ab10.png)

It detected something, but they have a very odd shape, and the object labels are also not "cell" in the output image.

Do you have a quick solution to fix this issue?

**Comment by ChristofferEdlund** [comment]
Hi there csmolnar!

For each model we also provide a config file [found here.](https://github.com/sartorius-research/LIVECell/tree/main/model)

Download the config file of the model you are after and then add the following code:

```
cfg = get_cfg()
cfg.merge_from_file("/path/to/config.yaml")
cfg.merge_from_list(['MODEL.WEIGHTS', os.path.join(models_path, "LIVECell_anchor_free_model.pth")])
```

Let me know if that helped fix your problem of if there is further issues. 

Kindly,
Christoffer

**Comment by ProBuro** [comment]
> I am trying to use the trained LIVECell model. To do so, first I have set up a google colab environment, and have tried to make predictions on some of the original training images. I followed the installation steps for LIVECell, and I combined it with a general Detectron2 model visualization tutorial.
> 
> Here is the main code I use:
> 
> ```
> # Register training dataset
> from detectron2.data.datasets import register_coco_instances
> from detectron2.data import MetadataCatalog, DatasetCatalog
> 
> register_coco_instances("LIVECell", {}, data_path + "livecell_coco_train.json", data_path + "/images/livecell_train_val_images")
> cells_metadata = MetadataCatalog.get("LIVECell")
> dataset_dicts = DatasetCatalog.get("LIVECell")
> 
> # Load trained model
> from detectron2.engine import DefaultTrainer
> from detectron2.engine import DefaultPredictor
> from detectron2.config import get_cfg
> 
> cfg = get_cfg()
> cfg.merge_from_list(['MODEL.WEIGHTS', os.path.join(models_path, "LIVECell_anchor_free_model.pth")])
> cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.25   # set the testing threshold for this model
> predictor = DefaultPredictor(cfg)
> 
> # Predict on training images
> from google.colab.patches import cv2_imshow
> from detectron2.utils.visualizer import Visualizer
> from detectron2.utils.visualizer import ColorMode
> 
> d = dataset_dicts[300] # choosing a random image
> img = cv2.imread(d["file_name"])
> outputs = predictor(img)
> instances = outputs['instances']
> v = Visualizer(img[:, :, ::-1],
>                    scale=1, 
>                    instance_mode=ColorMode.IMAGE_BW   # remove the colors of unsegmented pixels
>     )
> v = v.draw_instance_predictions(instances.to("cpu"))
> cv2_imshow(v.get_image()[:, :, ::-1])
> ```
> 
> And this is what I get as the result
> 
> ![pred_image300](https://user-images.githubusercontent.com/18211142/140103586-ec1b4c4a-4ea7-4f43-a0bf-7628af61ab10.png)
> 
> It detected something, but they have a very odd shape, and the object labels are also not "cell" in the output image.
> 
> Do you have a quick solution to fix this issue?

check the dimensions of the image. it looks like your dimensions are either confused (height, width) or the display is not taking place at the dimensions at which the training took place

**Comment by ChristofferEdlund** [comment]
@csmolnar have you tried my suggested changes and did that fix the predictions for you?

Let me know if it works so I can close this issue if that is the case, or try to further help you if there is still an issue.

Kindly,
Christoffer

**Comment by csmolnar** [comment]
Hi @ChristofferEdlund,

I was not able to make it work with the anchor free model (that package does not have an option for installation with pip), but I could load the anchor-based model with your suggestions.

Thank you!

**Comment by csmolnar** [comment]
Do the models have a specific input size for the images?
