### ISSUE TITLE
PCA visualization code

### ISSUE THREAD

**Issue by gallegi** [sartorius-research/LIVECell#8]
Can I receive the code that perform PCA on every cell type data and visualize them as demonstrated in the LIVECell paper?

**Comment by RickardSjogren** [comment]
Hi @gallegi, most of the code used for PCA is loading the morphology metrics, which we didn't share along with the paper. The actual PCA and visualization is standard use of scikit-learn and matplotlib. We have described how the morphology metrics were calculated in the methods section along with what libraries we used, so it should be quite straightforward to reproduce.

I see now that there is one small step for visualization that unfortunately isn't mentioned in the methods. Before you calculate the image-wise average morphology, I advise you to clip the values to avoid extreme values coming from a very small set of spurious tiny annotations that will skew the visualizatoin results. You basically:

```
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

df = ...            # Dataframe with loaded cell-wise morphology metrics.
value_cols = ...    # List of columns with the metrics you are interested in

df_transformed = pd.DataFrame(columns=value_cols, index=df.index)

for col in df.columns:
    values = df[col]
    # Clip extreme values, since some morphology metrics returns inf for spurious tiny annotations.
    low, high = np.percentile(values, [.1, 99.9])
    values = np.clip(values, low, high)
    df_transformed[col] = values

df_transformed['Image'] = df.Image  # Image-ID

image_means = df_transformed.groupby('Image').mean()

pca = PCA(2)
pipeline = Pipeline([
    ('scale', StandardScaler()),
    ('pca', pca)
]).fit(image_means)
scores = pipeline.transform(image_means)

make_a_fancy_plot(scores, pca, df_transformed)
```
